name: chart_line
description: chart line value.
version: 0.0.1
homepage:  https://www.linkedin.com/in/jacob-lartes

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
