name: chart_line
description: This package is to help work with simple graphics.
version: 0.0.2
homepage:  https://www.linkedin.com/in/jacob-lartes
repository:  https://github.com/Jacob-dvlp/chart-line
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
